[package]
name = "inst2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow_mesh = "0.1.4"
cpal = "0.15.2"
glow = "0.11.0"
glutin = "0.28"
minvect = "0.1.1"
ringbuf = "0.2"
